### ISSUE TITLE
Erro ao carregar auto load

### ISSUE THREAD

**Issue by poweriguana** [smartsolucoesgo/sendMyZap#2]
Segui o processo de instalação e alterei o arquivo index.php conforme descrito no readme, instalei o banco de dados e alterei o config, porém, ao tentar iniciar, recebi o seguinte erro: 

```
Warning: require(/home/meudominio/pubic_html/app/vendor/autoload.php): Failed to open stream: No such file or directory in /home/meudominio/public_html/index.php on line 11

Fatal error: Uncaught Error: Failed opening required '/home/meudominio/pubic_html/app/vendor/autoload.php' (include_path='.:') in /home/meudominio/public_html/index.php:11 Stack trace: #0 {main} thrown in /home/meudominio/public_html/index.php on line 11
```

Verifiquei e os arquivos estão disponíveis no caminho informado, e com as devidas permissões, mas sem sucesso.

**Comment by smartsolucoesgo** [comment]
Poderia postar um print de como está seu índex ?

**Comment by poweriguana** [comment]
Consegui resolver a parte do index, porém, agora, logo após realizar o login, retorna erro 404. Está instalado em subdomínio (sendmyzap.meudominio.com.br). Permissões ok e .htaccess presente.

**Comment by smartsolucoesgo** [comment]
seu dominio esta usando ssl, e por isso..
va no seu banco de dados, ta tabela de configuracoes e mude o protocol que por padrao vem http e mude para https e tente novamente

**Comment by poweriguana** [comment]
Reiniciar o php resolveu.
